### PR TITLE
#66 added title-bar icon

### PR DESCRIPTION
**Pull request by gurungrahul2**
there is no icon for the website, i think having a basic icon which 
matches the theme of website looks cool.

### CODE REVIEW

**Comment by egaga** [comment]
Where is that icon from. Could you provide it with a license, please?

**Comment by gurungrahul2** [comment]
found it from iconsets, and they allow their icons to be used independently. License http://iconsetc.com/license/

**Comment by gurungrahul2** [comment]
i can provide any other icon (designed by me) which will atleast look better than that default logo.

**Comment by egaga** [comment]
Yes, that would be fine, thank you.

**Comment by gurungrahul2** [comment]
how about this one ? made by me, used colors combinations used in openvim website.

**Comment by egaga** [comment]
That's good for me! Thank you.

**Pull request merged**
